### PR TITLE
Update usbCameraFrameGrabber.cpp for new opencv

### PR DESCRIPTION
**Pull request by mileticveljko**
I updated camera parameters settings with fresh opencv API

### CODE REVIEW

**Review by cbachhuber — APPROVED** [review]
This is great, thank you!

**Comment by cbachhuber** [comment]
@mileticveljko I noted that the build was pretty broken. I pushed [some commits](https://github.com/cbachhuber/CppVideoStreamer/compare/399932a308c324d41b30eed7eb10378329223fbf..b21dff672012cd0a235723d203e0232255397438) that fixed the build on my machine. With these, can you build, too?

If I had too much time on my hands, I'd add CI to this repo. Let's see if this ever happens 😅

**Comment by mileticveljko** [comment]
Hey @cbachhuber,
Build works great.

**Comment by cbachhuber** [comment]
Just FYI: we now have [continuous building of the code in this repo](https://github.com/cbachhuber/CppVideoStreamer/blob/43e3aae3e6ded03aa75d91b850f2f9173824bb6b/.github/workflows/build.yml), avoiding broken code 👍 

See also this [sample build](https://github.com/cbachhuber/CppVideoStreamer/actions/runs/5892638695/job/15982380636).

**Pull request merged**
